var weatherEl = ['temp~CurrentTemp'
				, 'tempdeg~Temp w/degree'
				, 'tempdegplus~Temp w/degree and type'
				, 'icon~Weather Icon'
				, 'high~CurrentHigh'
				, 'highdeg~High w/degree'
				, 'highdegplus~High w/degree and type'
				, 'low~CurrentHigh'
				, 'lowdeg~High w/degree'
				, 'lowdegplus~High w/degree and type'
				, 'highdashlow~High-Low'
				, 'highslashlow~High/Low'
				, 'highdashlowdeg~High-Low + deg'
				, 'highslashlowdeg~High/Low + deg'
				, 'city~Current City'
				, 'condition~Current Weather'
				, 'humidity~Current Humidity'
				, 'windchill~Current Wind Chill'
				, 'wind~Current Wind Speed'
				, 'winddirection~Current Wind Direction'
				, 'visibility~Current Visibility'
				, 'rain~Chance of rain'
				, 'dewpoint~Current DewPoint'
				, 'feelslike~Current Feel Temp'
				, 'feelslikedeg~Current Feel Temp + deg'
				, 'sunrise~Sunrise Time'
				, 'sunset~Sunset Time'
				, 'update~Last Updated'];
var clockEl = ['clock~12:00'
				, 'clockline~12|00'
				, 'zclock~01:00'
				, 'clockpm~12:00am'
				, 'zhour~05'
				, 'hour~12'
				, 'minute~30'
				, 'pm~pm'
				, 'ttext~Five Thirty'
				, 'htext~Five'
				, 'mtext~Thirty'
				, 'date~10'
				, 'prevdate~9'
				, 'nextdate~11'
				, 'dateplus~10th'
				, 'day~Sunday'
				, 'nextday~Monday'
				, 'yestday~Saturday'
				, 'sday~Sun'
				, 'snextday~Mon'
				, 'sprevday~Sat'
				, 'datetext~Tenth'
				, 'datestring~Day, Month Date'
				, 'datedotmonth~5.June'
				, 'dateslashmonth~5/June'
				, 'datedash~day-month-date'
				, 'datemonth~Date Month'
				, 'monthstring~Month with date plus abbrev'
				, 'month~Feburary'
				, 'nextmonth~March'
				, 'prevmonth~January'
				, 'monthdot~Month.Date'
				, 'monthline~Month|Date|Year'
				, 'smonth~Jan'
				, 'snextmonth~Feb'
				, 'sprevmonth~Dec'
				, 'mdy~5/10/2015'
				, 'year~2015'];
var systemEl = ['name~Displays name of the phone'
				, 'firmware~Current firmware'
				, 'battery~Current battery percent'
				, 'batterypercent~Current battery plus percent'
				, 'unlock~text when taped unlocks device'
				, 'chargingtxt~Charging'];
var miscEl = ['text~Allows custom text display'];
var fontArray = ['bebasbold'
				,'bebaslight'
				,'bebasneue'
				,'bebasneueregular'
				,'codebold'
				,'codelight'
				,'nexabold'
				,'nexabolder'
				,'nexalight'
				,'robotobold'
				,'robotolight'
				,'robotoregular'];